### registerRequest
GET http://localhost:8080/bank/user/registerRequest?content=json

### nextCaptcha
GET http://localhost:8080/bank/user/nextCaptcha?content=json&requestNo=184729215172608100000

### partnerRegister
POST http://localhost:8080/bank/user/partnerRegister
Content-Type: application/x-www-form-urlencoded

content=json&requestNo=326229952351436900000&captcha=32872&name=pill&phone=19999991111&registerDay=2022-01-01&certificateNo=464353454365546&creditCode=435353453&city=杭州市&legalPerson=zoro&legalPersonCertificateNo=520223199009233457


### personRegister
POST http://localhost:8080/bank/user/personRegister
Content-Type: application/x-www-form-urlencoded

content=json&requestNo=326229952351436900000&captcha=2989&partnerUserNo=227456499004211300000&name=zoro&phone=19999991111&certificateType=PERSON&certificateNo=520223199009233459&accountType=LENDER


