package io.army.generator;

import io.army.ArmyAccessException;
import io.army.ArmyRuntimeException;
import io.army.ErrorCode;

public class AutoGeneratedKeyException extends ArmyAccessException {

    public AutoGeneratedKeyException(ErrorCode errorCode, String format, Object... args) {
        super(errorCode, format, args);
    }

    public AutoGeneratedKeyException(ErrorCode errorCode, Throwable cause, String format, Object... args) {
        super(errorCode, cause, format, args);
    }
}
