package io.army.criteria;

import io.army.criteria.impl.SQLs;

import javax.annotation.Nullable;

import io.army.meta.FieldMeta;

import java.util.List;
import java.util.function.BiFunction;
import java.util.function.Consumer;
import java.util.function.Function;
import java.util.function.Supplier;

/**
 * <p>
 * This interface representing primary INSERT statement.This interface is base interface of below:
 *     <ul>
 *         <li>{@link Insert}</li>
 *         <li>{@link io.army.criteria.dialect.ReturningInsert}</li>
 *     </ul>
 * </p>
 *
 * @since 1.0
 */
public interface InsertStatement extends DmlStatement {


    /**
     * <p>
     * This interface representing the capacity ending INSERT statement.
     * </p>
     * <p>
     * <strong>Note:</strong><br/>
     * Application developer isn't allowed to directly use this interface,so you couldn't declare this interface type variable
     * ,because army don't guarantee compatibility to future distribution.
     * </p>
     *
     * @since 1.0
     */
    @Deprecated
    interface _InsertSpec extends _DmlInsertClause<InsertStatement> {

    }

    interface _MigrationOptionClause<R> {

        R migration();
    }

    /**
     * <p>
     * This interface representing the option prefer output literal when output domain column,but not contain
     * comment expression
     * </p>
     * <p>
     * <strong>Note:</strong><br/>
     * Application developer isn't allowed to directly use this interface,so you couldn't declare this interface type variable
     * ,because army don't guarantee compatibility to future distribution.
     * </p>
     *
     * @since 1.0
     */
    interface _PreferLiteralClause<R> {
        R literalMode(LiteralMode mode);
    }


    /**
     * @since 1.0
     */
    interface _NullOptionClause<R> {

        R nullMode(NullMode mode);
    }


    interface _IgnoreReturnIdsOptionClause<R> {

        /**
         * For domain insert mode ony.
         * <p>
         * The effect is that army don't return id that is generated by database to domain bean,
         * so if you invoke getId() method of domain bean,then always return null.
         * </p>
         * <p>
         * satisfy all below:
         *      <ul>
         *          <li>exists conflict clause,eg:MySQL ON DUPLICATE KEY,PostgreSQL ON CONFLICT</li>
         *          <li>non-migration mode,see {@link _MigrationOptionClause#migration()}</li>
         *          <li>{@link io.army.annotation.GeneratorType} of primary key is {@link io.army.annotation.GeneratorType#POST}</li>
         *          <li>insert table is {@link io.army.meta.SingleTableMeta} type</li>
         *          <li>domain insert mode</li>
         *          <li>insert multi-row</li>
         *          <li>don't support RETURNING clause or conflict clause is ignorable(eg:DO NOTHING,WHERE)</li>
         *      </ul>
         *      you have to specified this insert option or throw {@link CriteriaException}.
         * </p>
         */
        R ignoreReturnIds();

    }

    interface _StaticColumnUnaryClause<T> {

        _StaticColumnUnaryClause<T> comma(FieldMeta<T> field);

    }


    interface _StaticColumnDualClause<T> extends _StaticColumnUnaryClause<T> {

        @Override
        _StaticColumnDualClause<T> comma(FieldMeta<T> field);

        _StaticColumnDualClause<T> comma(FieldMeta<T> field1, FieldMeta<T> field2);

    }


    interface _StaticColumnCommaQuadraClause<T> extends _StaticColumnDualClause<T> {

        @Override
        _StaticColumnCommaQuadraClause<T> comma(FieldMeta<T> field);

        @Override
        _StaticColumnCommaQuadraClause<T> comma(FieldMeta<T> field1, FieldMeta<T> field2);

        _StaticColumnCommaQuadraClause<T> comma(FieldMeta<T> field1, FieldMeta<T> field2, FieldMeta<T> field3);

        _StaticColumnCommaQuadraClause<T> comma(FieldMeta<T> field1, FieldMeta<T> field2, FieldMeta<T> field3,
                                                FieldMeta<T> field4);

    }

    interface _StaticColumnSpaceClause<T> {

        _StaticColumnUnaryClause<T> space(FieldMeta<T> field);


        _StaticColumnDualClause<T> space(FieldMeta<T> field1, FieldMeta<T> field2);

        _StaticColumnCommaQuadraClause<T> space(FieldMeta<T> field1, FieldMeta<T> field2, FieldMeta<T> field3,
                                                FieldMeta<T> field4);

    }


    interface _ColumnListParensClause<T, R> {


        /**
         * <p>
         * INSERT static column list parens clause
         * </p>
         */
        R parens(Consumer<_StaticColumnSpaceClause<T>> consumer);

        /**
         * <p>
         * INSERT dynamic column list parens clause
         * </p>
         *
         * @param space see {@link SQLs#SPACE}
         */
        R parens(SQLs.SymbolSpace space, Consumer<Consumer<FieldMeta<T>>> consumer);

    }


    interface _QueryInsertSpaceClause<T extends Item, R extends Item> {

        T space();

        R space(Function<T, R> function);

        R space(Supplier<SubQuery> supplier);

    }


    interface _ColumnDefaultClause<T> {

        _ColumnDefaultClause<T> defaultValue(FieldMeta<T> field, Expression value);

        _ColumnDefaultClause<T> defaultValue(FieldMeta<T> field, Supplier<Expression> supplier);

        _ColumnDefaultClause<T> defaultValue(FieldMeta<T> field, Function<FieldMeta<T>, Expression> function);

        <E> _ColumnDefaultClause<T> defaultValue(FieldMeta<T> field, BiFunction<FieldMeta<T>, E, Expression> operator, @Nullable E value);

        <E> _ColumnDefaultClause<T> defaultValue(FieldMeta<T> field, SQLs.SymbolSpace space,
                                                 BiFunction<FieldMeta<T>, E, Expression> operator, Supplier<E> supplier);

        <K, V> _ColumnDefaultClause<T> defaultValue(FieldMeta<T> field, BiFunction<FieldMeta<T>, V, Expression> operator,
                                                    Function<K, V> function, K key);


        _ColumnDefaultClause<T> ifDefault(FieldMeta<T> field, Supplier<Expression> supplier);

        _ColumnDefaultClause<T> ifDefault(FieldMeta<T> field, Function<FieldMeta<T>, Expression> function);

        <E> _ColumnDefaultClause<T> ifDefault(FieldMeta<T> field, BiFunction<FieldMeta<T>, E, Expression> operator, Supplier<E> supplier);

        <K, V> _ColumnDefaultClause<T> ifDefault(FieldMeta<T> field, BiFunction<FieldMeta<T>, V, Expression> operator,
                                                 Function<K, V> function, K key);
    }

    /**
     * @since 1.0
     */
    interface _StaticColumnDefaultClause<T, R extends _ColumnDefaultClause<T>> extends _ColumnDefaultClause<T> {

        @Override
        R defaultValue(FieldMeta<T> field, Expression value);

        @Override
        R defaultValue(FieldMeta<T> field, Supplier<Expression> supplier);

        @Override
        R defaultValue(FieldMeta<T> field, Function<FieldMeta<T>, Expression> function);

        @Override
        <E> R defaultValue(FieldMeta<T> field, BiFunction<FieldMeta<T>, E, Expression> operator, @Nullable E value);


        @Override
        <E> R defaultValue(FieldMeta<T> field, SQLs.SymbolSpace space, BiFunction<FieldMeta<T>, E, Expression> operator, Supplier<E> supplier);

        @Override
        <K, V> R defaultValue(FieldMeta<T> field, BiFunction<FieldMeta<T>, V, Expression> operator,
                              Function<K, V> function, K key);

        @Override
        R ifDefault(FieldMeta<T> field, Supplier<Expression> supplier);

        @Override
        R ifDefault(FieldMeta<T> field, Function<FieldMeta<T>, Expression> function);

        @Override
        <E> R ifDefault(FieldMeta<T> field, BiFunction<FieldMeta<T>, E, Expression> operator, Supplier<E> supplier);

        @Override
        <K, V> R ifDefault(FieldMeta<T> field, BiFunction<FieldMeta<T>, V, Expression> operator,
                           Function<K, V> function, K key);

    }

    interface _DynamicColumnDefaultClause<T, R> {

        R defaults(Consumer<_ColumnDefaultClause<T>> consumer);

        R ifDefaults(Consumer<_ColumnDefaultClause<T>> consumer);
    }

    interface _FullColumnDefaultClause<T, R extends _ColumnDefaultClause<T>>
            extends _StaticColumnDefaultClause<T, R>, _DynamicColumnDefaultClause<T, R> {

    }


    /**
     * @since 1.0
     */
    interface _DomainValueClause<T, VR> {

        <TS extends T> VR value(TS domain);

        <TS extends T> VR value(Supplier<TS> supplier);

        <TS extends T> VR values(List<TS> domainList);

        <TS extends T> VR values(Supplier<List<TS>> supplier);

    }





    interface _ChildPartClause<CR> {

        CR child();

    }

    interface _ParentInsert<CT extends Item> extends Insert, _ChildPartClause<CT> {

    }

    interface _ParentInsert20<I extends Item, T extends Item> extends _ParentInsert<T>, _StaticSpaceClause<I> {

    }


    interface _StaticColumnValueClause<T> {

        _StaticColumnValueClause<T> comma(FieldMeta<T> field, Expression value);

        _StaticColumnValueClause<T> comma(FieldMeta<T> field, Supplier<Expression> supplier);

        _StaticColumnValueClause<T> comma(FieldMeta<T> field, Function<FieldMeta<T>, Expression> function);

        <E> _StaticColumnValueClause<T> comma(FieldMeta<T> field, BiFunction<FieldMeta<T>, E, Expression> funcRef, @Nullable E value);

        <E> _StaticColumnValueClause<T> comma(FieldMeta<T> field, SQLs.SymbolSpace space, BiFunction<FieldMeta<T>, E, Expression> funcRef, Supplier<E> supplier);

        <K, V> _StaticColumnValueClause<T> comma(FieldMeta<T> field, BiFunction<FieldMeta<T>, V, Expression> funcRef, Function<K, V> function, K key);

        _StaticColumnValueClause<T> ifComma(FieldMeta<T> field, Supplier<Expression> supplier);

        _StaticColumnValueClause<T> ifComma(FieldMeta<T> field, Function<FieldMeta<T>, Expression> function);

        <E> _StaticColumnValueClause<T> ifComma(FieldMeta<T> field, BiFunction<FieldMeta<T>, E, Expression> funcRef, Supplier<E> supplier);


        <K, V> _StaticColumnValueClause<T> ifComma(FieldMeta<T> field, BiFunction<FieldMeta<T>, V, Expression> funcRef, Function<K, V> function, K key);

    }

    interface _StaticValueSpaceClause<T> {

        _StaticColumnValueClause<T> space(FieldMeta<T> field, Expression value);

        _StaticColumnValueClause<T> space(FieldMeta<T> field, Supplier<Expression> supplier);

        _StaticColumnValueClause<T> space(FieldMeta<T> field, Function<FieldMeta<T>, Expression> function);

        <E> _StaticColumnValueClause<T> space(FieldMeta<T> field, BiFunction<FieldMeta<T>, E, Expression> funcRef, @Nullable E value);

        <E> _StaticColumnValueClause<T> space(FieldMeta<T> field, SQLs.SymbolSpace space, BiFunction<FieldMeta<T>, E, Expression> funcRef, Supplier<E> supplier);


        <K, V> _StaticColumnValueClause<T> space(FieldMeta<T> field, BiFunction<FieldMeta<T>, V, Expression> funcRef, Function<K, V> function, K key);

        _StaticColumnValueClause<T> spaceIf(FieldMeta<T> field, Supplier<Expression> supplier);

        _StaticColumnValueClause<T> spaceIf(FieldMeta<T> field, Function<FieldMeta<T>, Expression> function);

        <E> _StaticColumnValueClause<T> spaceIf(FieldMeta<T> field, BiFunction<FieldMeta<T>, E, Expression> funcRef, Supplier<E> supplier);


        <K, V> _StaticColumnValueClause<T> spaceIf(FieldMeta<T> field, BiFunction<FieldMeta<T>, V, Expression> funcRef, Function<K, V> function, K key);


    }



    interface _ValuesParensClause<T, R extends Item> extends Item {

        R parens(Consumer<_StaticValueSpaceClause<T>> consumer);

        R parens(SQLs.SymbolSpace space, Consumer<Assignments<T>> consumer);
    }

    interface _StaticValuesClause<R> {

        R values();

    }

    interface _DynamicValuesClause<T, R> {

        R values(Consumer<ValuesConstructor<T>> consumer);

    }


    /**
     * <p>
     * This interface representing SET assignment_list clause in INSERT statement.
     * </p>
     * <p>
     * <strong>Note:</strong><br/>
     * Application developer isn't allowed to directly use this interface,so you couldn't declare this interface type variable
     * ,because army don't guarantee compatibility to future distribution.
     * </p>
     */
    interface _StaticAssignmentSetClause<T, R> extends Item {

        R set(FieldMeta<T> field, Expression value);

        R set(FieldMeta<T> field, Supplier<Expression> supplier);

        R set(FieldMeta<T> field, Function<FieldMeta<T>, Expression> function);

        <E> R set(FieldMeta<T> field, BiFunction<FieldMeta<T>, E, Expression> valueOperator, @Nullable E value);

        <E> R set(FieldMeta<T> field, SQLs.SymbolEqual equal, BiFunction<FieldMeta<T>, E, Expression> valueOperator, Supplier<E> supplier);

        <K, V> R set(FieldMeta<T> field, BiFunction<FieldMeta<T>, V, Expression> valueOperator, Function<K, V> function, K key);


        R ifSet(FieldMeta<T> field, Supplier<Expression> supplier);

        R ifSet(FieldMeta<T> field, Function<FieldMeta<T>, Expression> function);

        <E> R ifSet(FieldMeta<T> field, BiFunction<FieldMeta<T>, E, Expression> valueOperator, Supplier<E> supplier);

        <K, V> R ifSet(FieldMeta<T> field, BiFunction<FieldMeta<T>, V, Expression> valueOperator, Function<K, V> function, K key);

    }



    interface _DynamicAssignmentSetClause<T, SD> {

        SD sets(Consumer<Assignments<T>> consumer);

        SD ifSets(Consumer<Assignments<T>> consumer);
    }


}
