spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    example:
      primary:
        url: jdbc:mysql://localhost:3306/army_test
        username: army_w
        password: army123
