spring:
  application:
    name: army-example
  mvc:
    contentnegotiation:
      favor-parameter: true
      parameter-name: content
      media-types:
        json: application/json
  profiles:
    active: sync,mysql
army:
  example:
    ddl:
      mode: UPDATE
    current:
      session:
        context: io.army.boot.sync.SpringCurrentSessionContext
    sql:
      log:
        show: true
    jdbc:
      large:
        update: false

