spring:
  application:
    name: army-example
  mvc:
    contentnegotiation:
      favor-parameter: true
      parameter-name: content
      media-types:
        json: application/json
  profiles:
    active: sync,mysql
army:
  pill:
    ddl:
      mode: UPDATE
    sync:
      session:
        context: io.army.boot.sync.SpringSessionContext
    sql:
      log:
        show: true
  bank:
    ddl:
      mode: UPDATE
    sync:
      session:
        context: io.army.boot.sync.SpringSessionContext
    sql:
      log:
        show: true

